// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6MkgANg4znjpVkrbMCUjnK
// Component: lyPMgW3Ahx
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import Button from "../../Button"; // plasmic-import: _KQKTBHwSiX/component
import { Iframe } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: CMDBvOhaI4s/codeComponent
import { Video } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: RhitNJW5Zu-/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 6MkgANg4znjpVkrbMCUjnK/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: lyPMgW3Ahx/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: L3S-zMEX2Er/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: mDR53dEgi75/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  iframe?: p.Flex<typeof Iframe>;
  htmlVideo?: p.Flex<typeof Video>;
  section?: p.Flex<"section">;
  foreground?: p.Flex<"div">;
  h2?: p.Flex<"h2">;
  h1?: p.Flex<"h1">;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.columns__h8EXk)}>
              <div className={classNames(projectcss.all, sty.column__wEsRa)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__p3Itt)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vgwDs)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___70OdL)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__fv7Z2)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__k5V0G)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__jfbRl)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__dU4D)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__zinI4)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cJs53)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vx1Y7)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__u3JAr)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tLVks)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__mIRdB
                      )}
                    />
                  </div>
                ) : null}
              </div>

              <div className={classNames(projectcss.all, sty.column__xp86)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__qKkMq)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__puDtz)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__np9T6)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iPywd)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div
                  className={classNames(projectcss.all, sty.freeBox___6WBjr)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__o5U1)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__eRynX)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__dzsir)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__d3BaG)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yePMg)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__q6PRc)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__plmXc)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__svqQt)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__atXp)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider___7Hugk)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__k0KqD)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zg6Ce)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rjVnp)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div
                  className={classNames(projectcss.all, sty.freeBox___3ZSMc)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__ssICh)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__yIJ)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__eswm)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dEsva)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ynAyy)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___0Upug)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__ywpdi)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__s8D3K)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column___1GSqP)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__kcLRn)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__q3Y5S)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cbpoi)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__x3ZSe)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__rCqft)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__lQ2R9)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column___4Wriy)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__bbA8Y)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6LT8H)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cjXx2)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___7Vd2)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox___8M5O)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__kzh5W)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__pr6Ua)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__tI4Dy)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___76Bpn)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__x95JK)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mw7Pu)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__czFdb)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__mz1Ah)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__lwqvE)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__jpiyS)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mZ7Uz)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rXzk6)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rvtnE)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__uCoxt)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__uqMis)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__zw27O)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__q6WFg)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___8REzb)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___27QgN)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iUDw2)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__czB6)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pnhm9)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__hFCy)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__hlHl)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__yYmRo)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__d9FCf)}>
                <Slider
                  className={classNames("__wab_instance", sty.slider__giNdG)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dcm71)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__sN1Uj)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2" as const
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gRqDx)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__h5NWw)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={
                      "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3" as const
                    }
                  />
                </Slider>

                <div className={classNames(projectcss.all, sty.freeBox__jhqD0)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__tEbn4)}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__da3Hb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z5VHq
                  )}
                >
                  {"Enter some text"}
                </div>

                <Iframe
                  data-plasmic-name={"iframe"}
                  data-plasmic-override={overrides.iframe}
                  className={classNames("__wab_instance", sty.iframe)}
                  src={"https://www.example.com" as const}
                />

                <Video
                  data-plasmic-name={"htmlVideo"}
                  data-plasmic-override={overrides.htmlVideo}
                  className={classNames("__wab_instance", sty.htmlVideo)}
                  src={
                    "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm" as const
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___5QOc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m1LP1
                  )}
                >
                  {"Enter some text"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0B58
                  )}
                >
                  {"Enter some text"}
                </div>

                <section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__srkut)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__lvxRl)}
                    />

                    <div
                      className={classNames(projectcss.all, sty.column__iJKuQ)}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__jxeg7)}
                  />

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground"}
                    data-plasmic-override={overrides.foreground}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6EhZw
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__o5Di3
                        )}
                      >
                        <h2
                          data-plasmic-name={"h2"}
                          data-plasmic-override={overrides.h2}
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2
                          )}
                        >
                          {"Proposing values"}
                        </h2>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tWxvV
                        )}
                      >
                        {
                          "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__v90HP
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bTw9U
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3ZmbK
                            )}
                          />
                        </div>

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__bn5Pp)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"865px" as const}
                          src={{
                            src: "/plasmic/blank_project/images/image.png",
                            fullWidth: 1730,
                            fullHeight: 1100,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                </section>
              </div>

              <div className={classNames(projectcss.all, sty.column__mxfN)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__nmRwn)}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__xSwNv)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zXxLp)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__akVfs)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tA82)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__upZhe)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5Kjlt)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mw1P)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ezbmh)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ribfK)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__eCacs)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xthgE)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xXfzw)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xV2A)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mcGh)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ukQ)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ybEc)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={
                    "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1" as const
                  }
                />
              </div>
            </div>

            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Welcome to your first page."}
            </h1>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__zlXm)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
            />

            <div className={classNames(projectcss.all, sty.freeBox__hEnoq)} />
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "iframe", "htmlVideo", "section", "foreground", "h2", "h1"],
  iframe: ["iframe"],
  htmlVideo: ["htmlVideo"],
  section: ["section", "foreground", "h2"],
  foreground: ["foreground", "h2"],
  h2: ["h2"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  iframe: typeof Iframe;
  htmlVideo: typeof Video;
  section: "section";
  foreground: "div";
  h2: "h2";
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iframe: makeNodeComponent("iframe"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    section: makeNodeComponent("section"),
    foreground: makeNodeComponent("foreground"),
    h2: makeNodeComponent("h2"),
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
